services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend


  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5433:5432"
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=maindb


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

# volumes:
#   postgres_data:
