services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # volumes:
    #   - ./backend:/home/node/app
    #   - /home/node/app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - db
    # watch for change for hot reload, volume mounting not work with tsx compile
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /home/node/app
          ignore:
            - .git
            - node_modules
            - .env
        - action: rebuild
          path: ./backend/package.json

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /home/node/app
          ignore:
            - .git
            - node_modules
            - .env
        - action: rebuild
          path: ./frontend/package.json

  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # redis:
  #   image: redis:latest

volumes:
  postgres_data:
