services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/home/node/app
      - /home/node/app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - db
  # frontend:
  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest

volumes:
  postgres_data:
